import "server-only";

import type { SkillBody } from "@/lib/domain/skill";

export type ApprovedSkill = {
  slug: string;
  version: number;
  body: SkillBody;
  citations: { claimPath: string; quote: string; sourceTitle: string | null }[];
};

/** Wrap a string as a safe double-quoted YAML scalar. */
function yamlQuote(value: string) {
  const escaped = value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n");
  return `"${escaped}"`;
}

/** One skill as a Claude Agent-Skill style SKILL.md section. */
function skillToMarkdown(skill: ApprovedSkill): string {
  const b = skill.body;
  const lines: string[] = [];
  lines.push("---");
  lines.push(`name: ${b.slug}`);
  lines.push(`description: ${yamlQuote(b.whenToUse)}`);
  lines.push(`category: ${b.category}`);
  if (b.owners.length) lines.push(`owners: [${b.owners.map(yamlQuote).join(", ")}]`);
  lines.push(`confidence: ${b.confidence}`);
  lines.push(`version: ${skill.version}`);
  lines.push("source: Cortex — the company brain");
  lines.push("---");
  lines.push("");
  lines.push(`# ${b.name}`);
  lines.push("");
  lines.push("## When to use");
  lines.push(b.whenToUse);
  if (b.triggers.length) {
    lines.push("");
    lines.push("## Triggers");
    for (const t of b.triggers) lines.push(`- ${t}`);
  }
  lines.push("");
  lines.push("## Steps");
  b.steps.forEach((s) => lines.push(`${s.order}. ${s.instruction}`));
  if (b.decisionRules.length) {
    lines.push("");
    lines.push("## Decision rules");
    for (const r of b.decisionRules) lines.push(`- IF ${r.condition} THEN ${r.action}`);
  }
  if (b.exceptions.length) {
    lines.push("");
    lines.push("## Exceptions");
    for (const e of b.exceptions) lines.push(`- ${e.situation}: ${e.handling}`);
  }
  if (b.guardrails.length) {
    lines.push("");
    lines.push("## Guardrails");
    for (const g of b.guardrails)
      lines.push(`- ${g.severity.toUpperCase()}: ${g.rule}`);
  }
  if (skill.citations.length) {
    lines.push("");
    lines.push("## Citations");
    for (const c of skill.citations) {
      lines.push(`- (${c.sourceTitle ?? "source"}) "${c.quote}"`);
    }
  }
  return lines.join("\n");
}

export function toSkillMarkdown(
  workspaceName: string,
  skills: ApprovedSkill[],
): string {
  const header = [
    `# ${workspaceName} — Company Skills`,
    "",
    `Generated by Cortex. ${skills.length} approved skill${skills.length === 1 ? "" : "s"}.`,
    "Each skill is grounded in cited company sources. Load these into an agent to",
    "handle work the way this company actually does it.",
    "",
    "---",
    "",
  ].join("\n");
  return header + skills.map(skillToMarkdown).join("\n\n---\n\n") + "\n";
}

export function toSkillJson(workspaceName: string, skills: ApprovedSkill[]) {
  return {
    workspace: workspaceName,
    generator: "cortex",
    skillCount: skills.length,
    skills: skills.map((s) => ({
      ...s.body,
      version: s.version,
      citations: s.citations,
    })),
  };
}

export function toSkillYaml(workspaceName: string, skills: ApprovedSkill[]) {
  // Minimal YAML emitter for the export shape (avoids a yaml dependency).
  const json = toSkillJson(workspaceName, skills);
  return jsonToYaml(json);
}

function jsonToYaml(value: unknown, indent = 0): string {
  const pad = "  ".repeat(indent);
  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    return value
      .map((item) => {
        const rendered = jsonToYaml(item, indent + 1);
        if (typeof item === "object" && item !== null) {
          return `${pad}-\n${rendered}`;
        }
        return `${pad}- ${rendered.trimStart()}`;
      })
      .join("\n");
  }
  if (typeof value === "object" && value !== null) {
    return Object.entries(value)
      .map(([key, v]) => {
        if (typeof v === "object" && v !== null) {
          return `${pad}${key}:\n${jsonToYaml(v, indent + 1)}`;
        }
        return `${pad}${key}: ${scalar(v)}`;
      })
      .join("\n");
  }
  return `${pad}${scalar(value)}`;
}

function scalar(v: unknown): string {
  if (v === null) return "null";
  if (typeof v === "string") {
    return /[:#\-?[\]{}\n"\\]/.test(v) || v === "" ? yamlQuote(v) : v;
  }
  return String(v);
}
